### ISSUE TITLE
Add flag to ignore Parse method

### ISSUE THREAD

**Issue by oparkerj** [sblom/RegExtract#15]
I recently came into an issue where the existence of a Parse(string) method caused the extraction plan to fail unexpectedly.
I wished to Extract to a struct with 3 int fields using 3 capture groups. However, since the struct contains a static Parse(string) method, the extraction plan believed that this struct should only consume 1 capture group instead of the three, and threw an exception. Commenting out the parse method temporarily solved the issue, but I would like for this to be a flag I can specify.

**Comment by sblom** [comment]
That's a really good idea. Thinking about level of granularity here, it seems bad to ignore _all_ Parse methods on everything. Do you have any clever ideas for how we could allow you to pass an ignore-list?

**Comment by oparkerj** [comment]
Hmm, I didn't consider the case where you'd want to ignore one parse method and use another one.
The first thing that comes to my mind if you want to have full control is some kind of format string.
I'm thinking of the edge case where you have a type like `List<(Position, Position)>` and you'd like to skip the parse method for one of the positions but use it for the other.

**Comment by sblom** [comment]
That's an additional level of granularity that I hadn't considered. :)

I was thinking more along the lines of "I really want `int`s to `Parse` even if I want to disable `Parse`ing in your example."

Maybe we could start with just an optional argument that allows you to exclude types by name (or `Type`). This could probably be attached to the `Extract()` overloads or possibly only available if you request plan creation explicitly.

If you have thoughts on where or how the format string might go for the more fine-grained version, I'm all ears.

**Comment by sblom** [comment]
Revisiting a handful of suggestion issues like this one.

I can totally reproduce this:
```csharp
ExtractionPlan<test>.CreatePlan(new Regex(@"(\d+) (\d+) (\d+)")).ToString("x").Dump();

struct test {
    public test(int a, int b, int c)
    {}

    public static test Parse(string str)
    {
        return new test();
    }
}
```

Resulting extraction Plan:
```
StaticParseMethod<test>[0] ()

↓----↓ ↓----↓ ↓----↓₀
(\d+)₁ (\d+)₂ (\d+)₃ 
```
