### ISSUE TITLE
Use `PolySharp` instead of self defining `IsExternalInit`

### ISSUE THREAD

**Issue by viceroypenguin** [sblom/RegExtract#19]
https://github.com/Sergio0694/PolySharp

**Comment by sblom** [comment]
Oooh, neat.

**Comment by viceroypenguin** [comment]
> Wait, tho. Does this help when you're a library project? RegExtract is going to have to ship with these types one way or another.

Yup. I use it in all of my OSS libraries. You can see it in [SuperLinq](https://github.com/viceroypenguin/SuperLinq/blob/master/Directory.Build.props), [Going.Plaid](https://github.com/viceroypenguin/Going.Plaid/blob/master/src/Plaid/Plaid.csproj), etc.
